name: Maven integration Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - ci/**

jobs:
  integration-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Integration Tests
        run: ./mvnw clean integration-test
